apps/directory/urls.py
from django.urls import path

from apps.directory.views import BulkImportView

from apps.directory.views import  TeacherListView, TeacherDetailView, HomePage, UserLoginView


app_name = "directory"


urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    path("login/", UserLoginView.as_view(), name="login"),
    path("teacher-list", TeacherListView.as_view(), name="teacher_list"),
    path("teacher-import", BulkImportView.as_view(), name="teacher_import"),
    path("teacher-detail/<slug:slug>", TeacherDetailView.as_view(), name="teacher_detail"),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.directory.urls", namespace="directory")),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/directory/models.py
import uuid
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.utils.text import  slugify

from apps.directory.utils import get_upload_path
from apps.directory.managers import TeacherManager

class TimestampModel(models.Model):
    """
    Abstract Model for timestamp.
    """

    created_at = models.DateTimeField(_("created at"), auto_now_add=True)
    updated_at = models.DateTimeField(_("updated at"), auto_now=True)

    class Meta:
        abstract = True


class Subject(TimestampModel):
    """
    Store subject information
    """

    name = models.CharField(max_length=50, primary_key=True)

    class Meta:
        verbose_name = _("subject")
        verbose_name_plural = _("subjects")

    def __str__(self):
        return self.name

    def clean(self, *args, **kwargs) -> None:
        self.name = self.name.lower()
        return super().clean(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("subject_detail", kwargs={"pk": self.pk})


class Teacher(TimestampModel):
    """
    To store teacher information
    """

    email_address = models.EmailField(
        _("email_address"), max_length=50, primary_key=True
    )
    slug = models.SlugField(blank=True, unique=True)
    first_name = models.CharField(_("first name"), max_length=150)
    last_name = models.CharField(_("last name"), max_length=150)
    phone_number = models.CharField(_("phone number"), max_length=15)
    profile_picture = models.ImageField(
        _("profile picture"),
        max_length=255,
        upload_to=get_upload_path,
        null=True,
        blank=True,
    )
    room_number = models.CharField(_("room number"), max_length=5)
    subjects = models.ManyToManyField(Subject)

    objects = TeacherManager()

    class Meta:
        verbose_name = _("teacher")
        verbose_name_plural = _("teachers")

    def __str__(self):
        return self.email_address

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = uuid.uuid4()
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("teacher_detail", kwargs={"pk": self.email_address})

    def get_first_letter_of_last_name(self):
        return self.last_name[0] if self.last_name else ""

apps/directory/forms.py
from django.contrib.auth.forms import AuthenticationForm

class UserAuthenticationForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"

apps/directory/views.py
import tablib
from django.db.models.functions import Lower, Substr
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages
from django.contrib.auth.views import LoginView
from django.views.generic import ListView, DetailView, TemplateView

from apps.directory.mixins import LoggedInUserRequired
from apps.directory.models import Subject, Teacher
from apps.directory.resources import TeacherResource
from apps.directory.forms import UserAuthenticationForm


class HomePage(TemplateView):
    template_name = 'home.html'


class UserLoginView(LoginView):
    authentication_form = UserAuthenticationForm
    template_name = "authentication/login.html"
    redirect_authenticated_user = True

class TeacherListView(ListView):
    model = Teacher
    context_object_name = "teachers"
    template_name = "directory/teachers_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        qs = (
            Teacher.objects.annotate(last_name_first_char=Lower(Substr("last_name", 1, 1)))
            .values("last_name_first_char")
            .distinct()
            .order_by("last_name_first_char")
        )
        context["last_name_first_letters"] = tuple(
            map(lambda obj: obj.get("last_name_first_char"), qs)
        )
        context["subjects"] = Subject.objects.all()
        return context

    def get_queryset(self):
        last_name_first_letter = self.request.GET.get("last_name_first_letter")
        subject_name = self.request.GET.get("subject")
        queryset = Teacher.objects.all()
        if last_name_first_letter:
            queryset = queryset.last_name_first_letter(last_name_first_letter)
        if subject_name:
            queryset = queryset.teach(subject_name)
        return queryset


class TeacherDetailView(DetailView):
    model = Teacher
    context_object_name = "teacher"
    template_name = "directory/teacher_detail.html"



class BulkImportView(LoggedInUserRequired, View):
    def get(self, request):
        template_name = "directory/teachers_import.html"
        return render(request, template_name)

    def post(self, request):
        teacher_resource = TeacherResource()
        dataset = tablib.Dataset()
        csv_file = request.FILES["csv_file"]
        upload_images = {fileobj.name: fileobj  for fileobj in request.FILES.getlist('profile_pictures_file')}
        data = dataset.load(csv_file.read().decode(), format="csv")
        result = teacher_resource.import_data(
            data, dry_run=True, raise_errors=True, collect_failed_rows=True,
        )
        if not result.has_errors():
            teacher_resource.import_data(data, dry_run=False, upload_images=upload_images)
            messages.add_message(request, messages.SUCCESS, 'Teacher imported successfully!')

        return redirect('directory:teacher_list')

apps/directory/templates/authentication/login.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="row ">
            <div class="col-sm-12 col-md-3 col-lg-3"></div>
            <div class="col-sm-12 col-md-6 col-lg-6">
                <div class="card shadow mt-5 border border-success">
                    <div class="card-header text-center">
                        <h4><strong>Teacher Directory User Log In</strong></h4>
                    </div>
                    <div class="card-body">
                        <form method="POST">{% csrf_token %}
                            <div class="text text-danger">
                                {{ form.non_field_errors }}
                            </div>
                            <div class="form-group">
                                {{ form.username.label }}
                                {{ form.username }}
                            </div>
                            <div class="form-group">
                                {{ form.password.label }}
                                {{ form.password }}
                            </div>
                            <div class="text-center">
                                <input type="submit" value="Log In" class="btn btn-block btn-primary" name="login"/>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-sm-12 col-md-3 col-lg-3"></div>
        </div>
    </div>
{% endblock content %}

apps/directory/templates/directory/auth_base.html
{% extends 'base.html' %}
{% block nav %}
    {% include 'components/navbar.html' %}
    {% if messages %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <ul class="messages">
            {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                {{ message }}
            </li>
            {% endfor %}
        </ul>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}
{% endblock nav %}

apps/directory/templates/directory/teacher_detail.html
{% extends 'directory/auth_base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="card shadow mt-5 border border-success">
            <div class="card-header">
                    <a class="text-decoration-none" href="{% url 'directory:teacher_list' %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
                        </svg>
                    </a>
                    <h5 class="d-inline-block ml-2">{{ teacher.first_name }} {{ teacher.last_name }}</h5>
            </div>
            <div class="card-body">
                <div class="row mb-5">
                    <div class="col-sm-12 col-md-4 col-lg-4"></div>
                    <div style="display: grid; place-items: center;" class="col-sm-12 col-md-4 col-lg-4">
                        <div class="profile">
                            {% if teacher.profile_picture %}
                                <img class="img-fluid profile-picture border border-success rounded-circle" src="{{ teacher.profile_picture.url }}" alt="Profile Picture"/>
                            {% else %}
                                <img class="img-fluid profile-picture" src="{% static 'images/default-profile.png' %}" alt="Profile Picture"/>
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-4 col-lg-4"></div>
                </div>
                <div class="row">
                    <div class="col-sm-6 col-md-6 col-lg-6">
                        <p><strong>First Name: </strong><span>{{ teacher.first_name }}</span></p>
                    </div>
                    <div class="col-sm-6 col-md-6 col-lg-6">
                        <p><strong> Name: </strong><span>{{ teacher.last_name }}</span></p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6 col-md-6 col-lg-6">
                        <p><strong>Email: </strong><span>{{ teacher.email_address }}</span></p>
                    </div>
                    <div class="col-sm-6 col-md-6 col-lg-6">
                        <p><strong>Phone Number: </strong><span><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-telephone" viewBox="0 0 16 16">
                            <path d="M3.654 1.328a.678.678 0 0 0-1.015-.063L1.605 2.3c-.483.484-.661 1.169-.45 1.77a17.568 17.568 0 0 0 4.168 6.608 17.569 17.569 0 0 0 6.608 4.168c.601.211 1.286.033 1.77-.45l1.034-1.034a.678.678 0 0 0-.063-1.015l-2.307-1.794a.678.678 0 0 0-.58-.122l-2.19.547a1.745 1.745 0 0 1-1.657-.459L5.482 8.062a1.745 1.745 0 0 1-.46-1.657l.548-2.19a.678.678 0 0 0-.122-.58L3.654 1.328zM1.884.511a1.745 1.745 0 0 1 2.612.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z"/>
                            </svg>  {{ teacher.phone_number }}</span></p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12 col-md-12 col-lg-12">
                        <p><strong>Room Number: </strong><span> {% if teacher.room_number %}{{ teacher.room_number }}{% else %} (No entries available) {% endif %}</span></p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12 col-md-12 col-lg-12">
                        <p><strong>Subjects:</strong></p>
                        {% if teacher.subjects %}
                            <ul>
                                {% for subject in teacher.subjects.all %}
                                    <li> <span class="badge badge-success text-capitalize">{{ subject.name }}</span></li>
                                {% endfor %}
                            </ul>
                        {% else %}
                            (No entries available)
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

apps/directory/templates/directory/teachers_import.html
{% extends 'directory/auth_base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5">
    <div class="jumbotron mt-3 border border-success p-4">
        <h1>Bulk Import Teacher</h1>
        <p class="lead">This csv importer will import the following fields in given orders: </p>
        <code>first_name,last_name,profile_picture,email_address,phone_number,room_number,subjects</code>
        <div class="col-sm-8 col-lg-10 mr-auto ml-auto border p-4">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <label for="csv_file">Select CSV file</label>
                <input type="file" accept="*.csv" class="file" name="csv_file" required>
                <label for="profile_pictures_file">Select Images</label>
                <input type="file" accept="*.JPG *.jpg *.PNG *.png" class="file" name="profile_pictures_file" multiple required>
                <button class="btn btn-lg btn-primary float-center" style="margin-left: 400px; margin-top: 2rem;" type="submit"> <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-upload" viewBox="0 0 16 16">
                    <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
                    <path d="M7.646 1.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 2.707V11.5a.5.5 0 0 1-1 0V2.707L5.354 4.854a.5.5 0 1 1-.708-.708l3-3z"/>
                    </svg>  Import</button>
            </form>
            <style>
                .file {
                    width: 300px;
                    height: 100px;
                    background: #f3efef;
                    padding: 8px;
                    border: 3px dashed #add2af;
                    position: relative;
                    cursor: pointer;
                }
            </style>
        </div>
    </div>
</div>
</div>
{% endblock %}

apps/directory/templates/directory/teachers_list.html
{% extends 'directory/auth_base.html' %}
{% load static %}
{% load query_params %}
{% block content %}
    <div class="container">
        <div class="card shadow mt-5 border border-success">
            <div class="card-header">
                <h4>Teacher List</h4>
            </div>
            <div class="card-body">
                <div class="filter">
                    <i class="bi bi-funnel"></i>
                    <p>
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-funnel" viewBox="0 0 16 16">
                            <path d="M1.5 1.5A.5.5 0 0 1 2 1h12a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-.128.334L10 8.692V13.5a.5.5 0 0 1-.342.474l-3 1A.5.5 0 0 1 6 14.5V8.692L1.628 3.834A.5.5 0 0 1 1.5 3.5v-2zm1 .5v1.308l4.372 4.858A.5.5 0 0 1 7 8.5v5.306l2-.666V8.5a.5.5 0 0 1 .128-.334L13.5 3.308V2h-11z"/>
                            </svg>
                        Filters: <a class="text-decoration-none" href="{{request.path}}"> <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-circle" viewBox="0 0 16 16">
                        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                        <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                        </svg> Clear All Filters</a></p>
                    <p>
                        <span> <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-book" viewBox="0 0 16 16">
                            <path d="M1 2.828c.885-.37 2.154-.769 3.388-.893 1.33-.134 2.458.063 3.112.752v9.746c-.935-.53-2.12-.603-3.213-.493-1.18.12-2.37.461-3.287.811V2.828zm7.5-.141c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492V2.687zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z"/>
                            </svg>
                            By Subject</span>
                        <select id="_subject">
                            <option {% if request.GET.subject == '' %}  selected {% endif %} value="{% append_query_params request subject='' %}">All</option>
                            {% for sub in subjects %}
                                <option {% if request.GET.subject == sub.name %}  selected {% endif %} value="{% append_query_params request subject=sub.name %}">{{ sub.name }}</option>
                            {% endfor %}
                        </select>
                    </p>
                    <p>
                        <span> <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-sort-alpha-down" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M10.082 5.629 9.664 7H8.598l1.789-5.332h1.234L13.402 7h-1.12l-.419-1.371h-1.781zm1.57-.785L11 2.687h-.047l-.652 2.157h1.351z"/>
                            <path d="M12.96 14H9.028v-.691l2.579-3.72v-.054H9.098v-.867h3.785v.691l-2.567 3.72v.054h2.645V14zM4.5 2.5a.5.5 0 0 0-1 0v9.793l-1.146-1.147a.5.5 0 0 0-.708.708l2 1.999.007.007a.497.497 0 0 0 .7-.006l2-2a.5.5 0 0 0-.707-.708L4.5 12.293V2.5z"/>
                            </svg>
                            By First Letter of Last Name: </span>
                        <a class="text-decoration-none" href="{% append_query_params request last_name_first_letter='' %}">
                            <span class="badge badge-light text-uppercase">
                                ALL
                            </span>
                        </a>
                        {% for letter in last_name_first_letters %}
                            <a class="text-decoration-none" href="{% append_query_params request last_name_first_letter=letter %}">
                                <span class="badge badge-light text-uppercase">
                                    {{letter}}
                                </span>
                            </a>
                        {% endfor %}
                    </p>
                </div>
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th id='th-first-name'>First Name</th>
                                <th id="th-last-name">Last Name</th>
                                <th id='th-email-address'>Email Address</th>
                                <th id='th-phone-number'> <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-telephone" viewBox="0 0 16 16">
                                    <path d="M3.654 1.328a.678.678 0 0 0-1.015-.063L1.605 2.3c-.483.484-.661 1.169-.45 1.77a17.568 17.568 0 0 0 4.168 6.608 17.569 17.569 0 0 0 6.608 4.168c.601.211 1.286.033 1.77-.45l1.034-1.034a.678.678 0 0 0-.063-1.015l-2.307-1.794a.678.678 0 0 0-.58-.122l-2.19.547a1.745 1.745 0 0 1-1.657-.459L5.482 8.062a1.745 1.745 0 0 1-.46-1.657l.548-2.19a.678.678 0 0 0-.122-.58L3.654 1.328zM1.884.511a1.745 1.745 0 0 1 2.612.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z"/>
                                    </svg>  Phone Number</th>
                                <th id='th-view-detail'>Goto Profile</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for teacher in teachers %}
                                <tr>
                                    <td>{{ teacher.first_name }}</td>
                                    <td>{{ teacher.last_name }}</td>
                                    <td>{{ teacher.email_address }}</td>
                                    <td>{{ teacher.phone_number }}</td>
                                    <td><a class="text-decoration-none" href="{% url 'directory:teacher_detail' teacher.slug %}"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-journal-plus" viewBox="0 0 16 16">
                                        <path fill-rule="evenodd" d="M8 5.5a.5.5 0 0 1 .5.5v1.5H10a.5.5 0 0 1 0 1H8.5V10a.5.5 0 0 1-1 0V8.5H6a.5.5 0 0 1 0-1h1.5V6a.5.5 0 0 1 .5-.5z"/>
                                        <path d="M3 0h10a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-1h1v1a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1v1H1V2a2 2 0 0 1 2-2z"/>
                                        <path d="M1 5v-.5a.5.5 0 0 1 1 0V5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0V8h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0v.5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1z"/>
                                        </svg> Detail</a></td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    {{ block.super }}
    <script type="text/javascript">
        var subject = document.querySelector("#_subject");
        subject.addEventListener("change", function(){
            window.location.href = this.value;
        });
    </script>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>
            {% if title %}
                {{ title }}
            {% else %}
                Teacher Directory
            {% endif %}
        </title>
        {% block stylesheet %}
            <link type="text/css" rel="stylesheet" href="{% static 'css/vendor/bootstrap.min.css' %}">
            <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}" />
        {% endblock stylesheet %}
    </head>
    <body>
        {% block nav %}
        {% endblock nav %}
        {% block content %}
        {% endblock content %}
        {% block footer %}
        {% endblock footer %}
        {% block script %}
            <script type="text/javscript" src="{% static 'js/vendor/jquery.min.js' %}"></script>
            <script type="text/javscript" src="{% static 'js/vendor/jquery-ajax.min.js' %}"></script>
            <script type="text/javscript" src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
            <script type="text/javscript" src="{% static 'js/vendor/popper.min.js' %}"></script>
        {% endblock script %}
    </body>
</html>

templates/components/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'directory:home' %}">Home</a>
    <a class="navbar-brand" href="{% url 'directory:teacher_list' %}">Teacher Directory</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-toggle"
        aria-controls="navbar-toggle" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbar-toggle">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'directory:teacher_import' %}">Import</a>
            </li>
        </ul>
    </div>
</nav>

templates/home.html
{% extends 'base.html' %}
{% block nav %}
    {% include 'components/navbar.html' %}
{% endblock nav %}
{% block content %}
<div class="container mt-5">
    <div class="jumbotron mt-4">
        <h1>School Teacher Directory App</h1>
        <p class="lead">This is directory app containing all the Teachers in a given school.</p>

        <p>Each teacher should have the following information</p>
        <ul>
            <li>First Name</li>
            <li>Last Name</li>
            <li>Profile picture</li>
            <li>Email Address</li>
            <li>Phone Number</li>
            <li>Room Number</li>
            <li>Subjects taught</li>
        </ul>
    </div>
</div>
</div>
{% endblock %}